---
title: "Module 5"
author: "Data Pirates"
date: "2022-10-05"
output: html_document
bibliography: DataPirates.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
For this project, our gruop will be investigating whether a person's body temperature varies with different levels of activity. According to a study by @lim2008human, physical activity causes a substantial increase in metabolic heat production, thus increasing body temperature. To further investigate this, the temperature of 4 different subjects during their rest time and after (fill in time once we record data in case we don't do 5 mins) minutes of activity will be recorded. 

# Methods
In order to determine the relationship between body temperature and activity level, each individual had their body temperature (°C) measured from their armpit for (however long we end up doing). After that has been recorded, the individual will proceed to do jumping jacks for (however long) and their body temperature from their armpit will be recorded a second time. This process will be done to all four individuals and their data will be recorded accordingly. 

# Results

# Discussion

# Author Contribution
Chris - Introduction, Methods
Alexa - Recorded, Saved, and Properly Named Data
Ellie - 
Tori - 
# References
